[project]
name = "loki-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.2",
    "requests>=2.32.4",
    "structlog>=25.4.0",
]
